name: Frontend CD

on:
  push:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Check Build
      run: npm run build
      env:
        CI: true    
    - name: Running remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
                cd /home/glugwebsite/lugnitdgp.github.io
                git checkout prod
                git pull origin prod
                npm run build
                cd ~
                sudo systemctl restart nginx
